ufunc 함수라 불림
- ndarray 내에 있는 데이터 원소별로 연산을 수행하는 함수
- 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 간단한 함수를
- 고속으로 수행 할 수 있는 벡터화된 래퍼 함수
- 함수의 종류
- 단항 유니버설 함수 : 하나의 인자를 받아서 반환
- 이항 유니버설 함수 : 두개의 인자를 받아서 단일 배열 반환
- url
    - https://docs.scipy.org/doc/numpy/reference/ufuncs.html#ufunc

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 제곱근
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
# 두개의 배열들의 각 index 와 일치되는 요소들끼리만 비교해서 최대값 구하기
x = np.random.randint(100, 999, size=3)
y = np.random.randint(100, 999, size=3)
print(x,y)

[263 221 296] [646 258 743]


In [8]:
np.minimum(x,y)

array([263, 221, 296])

In [9]:
# 단항 유니버설 함수
# 제곱근
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
data = data.reshape(3,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
data * data

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [14]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
data.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
data = np.dot(data,data.T)
data

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [17]:
data * data.T

array([[   196,   1444,   3844],
       [  1444,  15876,  45796],
       [  3844,  45796, 133956]])

# 차원 축소 집계 연산

In [25]:
x = np.array([1,32,131,1313, 13,124])

In [27]:
x

array([   1,   32,  131, 1313,   13,  124])

In [32]:
x.max()

1313

In [33]:
x.sum()

1614

In [35]:
x.argmax() # 가장 큰 데이터의 index값

3

In [36]:
a = np.sort(x)

In [37]:
a

array([   1,   13,   32,  124,  131, 1313])

In [38]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [39]:
b = np.sort(a)
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [42]:
b = np.sort(a, axis=0) # 열별로 오름차순
b

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [44]:
b = np.sort(a, axis=1)  # 행별로 오름차순
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [45]:
np.random.rand(5)

array([0.76335217, 0.90492717, 0.18299638, 0.38350464, 0.08100066])

In [53]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [56]:
np.random.rand(5)

array([0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497])

In [54]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])